services:
  nextcloud:
    restart: unless-stopped
    image: nextcloud:30.0.17
    container_name: nextcloud
    depends_on:
      - nextcloud_mariadb
      - nextcloud_redis
    labels:
      - traefik.enable=true
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.{{ local_domain }}`)"
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
    volumes:
      - "{{ appdata_path }}/nextcloud/data:/var/www/html"
      - "{{ storage_path }}:/storage"
    environment:
      - REDIS_HOST=nextcloud_redis
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ ntp_timezone }}"

  nextcloud_redis:
    restart: unless-stopped
    image: redis:alpine
    container_name: nextcloud_redis

  nextcloud_mariadb:
    restart: unless-stopped
    image: mariadb:10.5
    container_name: nextcloud_mariadb
    volumes:
      - "{{ appdata_path }}/nextcloud/db:/var/lib/mysql"
    environment:
      - MYSQL_AUTO_UPGRADE=1
      # - MYSQL_DISABLE_UPGRADE_BACKUP=1
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"
      - "MYSQL_PASSWORD={{ nextcloud_db_password }}"
      - "MYSQL_ROOT_PASSWORD={{ nextcloud_root_db_password }}"
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ ntp_timezone }}"